apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
  selector:
    app: elasticsearch
  type: {{ .Values.elasticsearch.service.type }}
