apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-kibana-pv
  namespace: efk
spec:
  capacity:
    storage: {{ .Values.kibana.persistence.size }}
  accessModes:
    - {{ .Values.kibana.persistence.accessMode }}
  storageClassName: {{ .Values.kibana.persistence.storageClass }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/{{ .Release.Name }}-kibana
