apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kibana-pvc
  namespace: efk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kibana.persistence.size }}
  storageClassName: {{ .Values.kibana.persistence.storageClass }}
