{{- if .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kibana-ingress
  labels:
    app: kibana
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  {{- range .Values.kibana.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Release.Name }}-kibana
            port:
              number: {{ $.Values.kibana.service.port }}
      {{- end }}
  {{- end }}
{{- end }}
