{{- if .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kibana
  annotations:
    {{- toYaml .Values.kibana.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.kibana.ingress.hosts | first }}
      http:
        paths:
          - path: {{ .Values.kibana.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-kibana
                port:
                  number: 5601
  {{- if .Values.kibana.ingress.tls }}
  tls:
    - secretName: {{ .Values.kibana.ingress.tls.secretName }}
      hosts:
        {{- toYaml .Values.kibana.ingress.tls.hosts | nindent 8 }}
  {{- end }}
{{- end }}
