apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
    - port: {{ .Values.kibana.service.port }}
  selector:
    app: kibana
  type: {{ .Values.kibana.service.type }}
