apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana
  namespace: efk
  labels:
    app: kibana
spec:
  replicas: {{ .Values.kibana.replicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: {{ .Values.kibana.securityContext.fsGroup }}
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/data && chown -R 1000:1000 /mnt/data"]
          volumeMounts:
            - name: kibana-data
              mountPath: /mnt/data
      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          ports:
            - containerPort: 5601
          securityContext:
            runAsUser: {{ .Values.kibana.securityContext.runAsUser }}
            runAsGroup: {{ .Values.kibana.securityContext.fsGroup }}
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://{{ .Release.Name }}-elasticsearch:9200"
          volumeMounts:
            - name: kibana-data
              mountPath: /usr/share/kibana/data
          livenessProbe:
            httpGet:
              path: /status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 5601
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: "{{ .Values.kibana.resources.limits.cpu }}"
              memory: "{{ .Values.kibana.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.kibana.resources.requests.cpu }}"
              memory: "{{ .Values.kibana.resources.requests.memory }}"
      volumes:
        - name: kibana-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-kibana-pvc
