apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana
  labels:
    app: kibana
spec:
  replicas: {{ .Values.kibana.replicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
        imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
        ports:
        - containerPort: 5601
        resources:
{{ toYaml .Values.kibana.resources | indent 10 }}
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://{{ .Release.Name }}-elasticsearch:9200"
        volumeMounts:
        - name: kibana-storage
          mountPath: /usr/share/kibana/data
      volumes:
      - name: kibana-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-kibana-pvc
