{{- if .Values.kibana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kibana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kibana.persistence.size }}
  storageClassName: {{ .Values.kibana.persistence.storageClass }}
{{- end }}
