apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana
  labels:
    app: kibana
spec:
  ports:
  - port: {{ .Values.kibana.service.port }}
    targetPort: 5601
    protocol: TCP
  selector:
    app: kibana
  type: {{ .Values.kibana.service.type }}
