apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-kibana-pv
spec:
  capacity:
    storage: {{ .Values.kibana.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ .Values.kibana.persistence.hostPath }}
