apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana
  labels:
    app: kibana
spec:
  replicas: {{ .Values.kibana.replicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      securityContext:
        runAsUser: {{ .Values.kibana.securityContext.runAsUser }}
        fsGroup: {{ .Values.kibana.securityContext.fsGroup }}

      # Init container to set permissions
      initContainers:
        - name: volume-permission-fix
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/kibana/data"]
          volumeMounts:
            - name: kibana-data
              mountPath: /usr/share/kibana/data

      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          ports:
            - containerPort: 5601
          resources:
{{ toYaml .Values.kibana.resources | indent 12 }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://{{ .Release.Name }}-elasticsearch:9200"
          volumeMounts:
            - name: kibana-data
              mountPath: /usr/share/kibana/data

            volumes:
        - name: kibana-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-kibana-pvc

