apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    {{- toYaml .Values.kibana.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.kibana.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: {{ .Values.kibana.service.port }}
