# Elasticsearch Configuration
elasticsearch:
  replicaCount: 1
  image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
  storageClassName: "gp2"
  storageSize: "10Gi"
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  service:
    type: ClusterIP
    port: 9200

# Fluent Bit Configuration
 fluentbit:
  enabled: true
  image: fluent/fluent-bit:2.1.0
  config:
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Parser docker
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
    outputs: |
      [OUTPUT]
          Name es
          Match *
          Host elasticsearch
          Port 9200
          Logstash_Format On
          Logstash_Prefix fluentbit
          Replace_Dots On
          Retry_Limit False

# Kibana Configuration
kibana:
  replicaCount: 1
  image: docker.elastic.co/kibana/kibana:8.10.0
  service:
    type: ClusterIP
    port: 5601
  ingress:
    enabled: true
    host: kibana.example.com
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
