# Elasticsearch Configuration
elasticsearch:
  replicaCount: 1
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "7.10.0"
    pullPolicy: IfNotPresent
  resources: {}
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "standard"

# Fluent Bit Configuration
fluentbit:
  image:
    repository: "fluent/fluent-bit"
    tag: "1.6.10"
    pullPolicy: IfNotPresent
  resources: {}
  config: {}

# Kibana Configuration
kibana:
  replicaCount: 1
  image:
    repository: "docker.elastic.co/kibana/kibana"
    tag: "7.10.0"
    pullPolicy: IfNotPresent
  resources: {}
  service:
    type: ClusterIP
    port: 5601
  ingress:
    enabled: false
    hosts:
      - host: "kibana.example.com"
        paths: ["/"]
