elasticsearch:
  replicaCount: 1
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "7.17.3"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "4Gi"
      cpu: "500m"
    limits:
      memory: "8Gi"
      cpu: "1"
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "standard"
  securityContext:
    fsGroup: 1000
    runAsUser: 1000

fluentbit:
  image:
    repository: "fluent/fluent-bit"
    tag: "1.6.10"
    pullPolicy: IfNotPresent
  resources: {}
  config:
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Parser docker
          Tag kube.*
          DB /var/log/flb_kube.db
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
    outputs: |
      [OUTPUT]
          Name es
          Match *
          Host elasticsearch-service
          Port 9200
          Index fluentbit

kibana:
  replicaCount: 1
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 7.17.3
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
  persistence:
    enabled: true
    size: 1Gi
    hostPath: /mnt/data/kibana
  service:
    type: ClusterIP
    port: 5601
  ingress:
    enabled: true  # Set to false if you don't want ingress
    annotations: {}
    path: /
    hosts:
      - "kibana.example.com"
    tls:
      - secretName: kibana-tls
        hosts:
          - "kibana.example.com"

